name: Show Commits
description: Show commits since last tag by printing them to a slack channel
inputs:
  header:
    description: 'Header line'
    required: true
    default: 'Create release'
outputs:
  release:
    description: "Release"
    value: ${{ steps.fetch.outputs.release }}
  result:
    description: "Results from Slack post"
    value: ${{ steps.notify.outputs.slack-result }}
runs:
  using: "composite"
  steps:
    - name: Fetch list of all commits since last tag
      id: fetch
      shell: bash -x {0}
      run: |
          tag=$(git describe --tags --abbrev=0 $GITHUB_SHA)
          output=$(git log --format=":black_small_square: %s" $tag.. | perl -pe 's/\n/\\n/g')
          echo "::set-output name=commits::$output"
          echo "::set-output name=release::$tag"
    - name: Send message with commits in release
      uses: archive/github-actions-slack@v2.0.0
      id: notify
      with:
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
        slack-channel: ${{ secrets.SLACK_CHANNEL_EXPERIMENTAL }}
        slack-text: ${{ inputs.header }} ${{ steps.fetch.outputs.release }}:\n${{ steps.fetch.outputs.commits }}
  
